### ISSUE TITLE
Blank screen after attempting to install another OS

### ISSUE THREAD

**Issue by jamesmortensen** [ming900518/macOS-Virtual-Machine#2]
Thank you for putting this solution together and thanks to Mrmacintosh for the great YouTube walkthrough.

I got a Monterey VM set up, and I thought I would also setup  Big Sur VM.  I knew I would need the macos Virtual Machine folder in the Library/Containers folder to be freed up for me to go through the DFU, firmware installation, and OS installation process again, so I attempted to rename it to Library/Containers/macos monterey virtual machine.

I also modified the plist.info file in the .app package generated by the xcode build so that it would look for disk.img in the renamed folder.

However, the screen just boots up a black screen.  I put everything back to how it was and am still getting the black screen.

There is nothing important on the VM, but I would love to learn more about this process and am wondering what modifying Info.plist did to the VM? Did this somehow mess with the signing process?  I have modified info.plist files before when creating apps.  I only changed CFBundleName and CFBundleExecutable, and when it didn't work, I changed them back to the original values.

**Comment by jamesmortensen** [comment]
I ended up attempting to restore the VM using Apple Configurator 2 and the IPSW firmware file, but this just wiped the image and factory reset the macOS Monterey installation, so I guess the big question is how can I create multiple Monterey and Big Sur VMs?  Also, how would I back them up? It seems backing up just the disk.img file may not be enough.  

At some point, I may try a few other experiments, and if I figure it out, I will update here.  Thanks again for putting this together.

**Comment by ming900518** [comment]
Hi James.
First of all, I strongly recommend you to switch to [this project](https://github.com/KhaosT/MacVM), KhaosT will provide much better support.
And I don't think Big Sur VM will be possible, because the Big Sur install image is not containing proper device information and drivers that are required for VM to start correctly.
Manually copy them from Monterey to Big Sur might work but I didn't try it though.

**Comment by jamesmortensen** [comment]
Thanks for the reply @ming900518 but I wasn't able to get Khaos's solution to work.  I'm just getting a file picker dialog, and I'm not entirely clear what I'm supposed to do with that.  https://github.com/KhaosT/MacVM/issues/12

I'll wait for Khaos's reply.  Cheers.

James

**Comment by jamesmortensen** [comment]
Just to follow up, when I clicked "New Document" in the file picker dialog, the UI appeared and I was able to proceed.  Hope it helps others.  Thank you.  I now have two macOS Monterey VM's, one running from this project and one from KhaosT/MacVM.
